In [86]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [87]:
import pandas as pd

In [88]:
df = pd.DataFrame(people)

In [89]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [90]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [91]:
df.columns = ['first_name','last_name', 'email']

In [92]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [93]:
df.columns = [x.upper() for x in df.columns]
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [94]:
df.columns = df.columns.str.replace('_',' ')
df

  FIRST NAME LAST NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [95]:
df.columns = df.columns.str.replace(' ','_')
df.columns = [x.lower() for x in df.columns] # Converte os nomes das colunas para letras minúsculas usando uma list comprehension.

In [96]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [97]:
df.rename(columns={'first_name':'first', 'last_name': 'last'}, inplace = True)
# Renomeia as colunas 'first_name' para 'first' e 'last_name' para 'last' usando o método rename do DataFrame.
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [98]:
df.loc[2] = ['John','Smith','JhonSmith@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith      JhonSmith@email.com

In [99]:
df.loc[2, ['last','email']]

last                   Smith
email    JhonSmith@email.com
Name: 2, dtype: str

In [100]:
df.loc[2, ['last','email']] = ['Matheus', 'Matheus@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [101]:
df.loc[2,'last'] = 'Carlos'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John   Carlos        Matheus@email.com

In [102]:

# Usando o método at para atualizar um valor específico
# O método at é mais rápido do que loc para acessar um único valor, pois é otimizado para esse tipo de operação.
df.at[2,'last'] = 'Matheus'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [103]:
filtro = (df['email'] == 'JaneDoe@email.com')
df.loc[filtro, 'last'] = 'Smith'
df

# É necessário usar o método loc para atualizar os valores
# pois ele permite acessar e modificar os valores de forma eficiente, especialmente quando se trata de condições ou filtros.
# O método at é mais adequado para acessar um único valor específico.

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane    Smith        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [104]:
filtro = (df['email'] == 'JaneDoe@email.com')
df.loc[filtro, 'last'] = 'Smith'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane    Smith        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [105]:
df['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          Matheus@email.com
Name: email, dtype: str

In [106]:
df['email'].str.upper() # Converte os valores da coluna 'email' para letras maiúsculas usando o método str.upper().

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@EMAIL.COM
2          MATHEUS@EMAIL.COM
Name: email, dtype: str

In [107]:
df['email'] = df['email'].str.upper()

# Pode ser usado o método str.lower() para converter os valores da coluna 'email' para letras minúsculas.
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane    Smith        JANEDOE@EMAIL.COM
2   John  Matheus        MATHEUS@EMAIL.COM

USANDO A FUNÇÃO .apply()

In [108]:
df['email'].apply(len) # Aplica a função len a cada valor da coluna 'email', retornando o comprimento de cada string de email.

0    23
1    17
2    17
Name: email, dtype: int64

In [109]:
def update_email(email):
    return email.upper()  # ou email.upper() para converter para maiúsculas

In [110]:
df['email'].apply(update_email) # Aplica a função update_email a cada valor da coluna 'email', convertendo os emails para letras maiúsculas.
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane    Smith        JANEDOE@EMAIL.COM
2   John  Matheus        MATHEUS@EMAIL.COM

In [111]:
df['email'] = df['email'].apply(update_email) # Atualiza a coluna 'email' com os valores convertidos para letras minúsculas usando a função update_email.
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane    Smith        JANEDOE@EMAIL.COM
2   John  Matheus        MATHEUS@EMAIL.COM

In [112]:
df.apply(len, axis = 'columns') # Aplica a função len a cada linha do DataFrame, retornando o número de colunas em cada linha.

0    3
1    3
2    3
dtype: int64

In [113]:
df.apply(len, axis='rows') # Aplica a função len a cada coluna do DataFrame, retornando o número de linhas em cada coluna.

first    3
last     3
email    3
dtype: int64

In [114]:
len(df.columns)

3

In [115]:
df.apply(pd.Series.min) # Aplica a função min a cada coluna do DataFrame, retornando o valor mínimo de cada coluna.
# Verifica o valor mínimo de cada coluna, o que pode ser útil para identificar o valor mais baixo em colunas numéricas ou a string mais "pequena" em colunas de texto.

first                      Corey
last                     Matheus
email    COREYMSCHAFER@GMAIL.COM
dtype: str

Usando a função applymap

In [116]:
df['email'].apply(len) # Aplica a função len a cada valor da coluna 'email', retornando o comprimento de cada string de email.

0    23
1    17
2    17
Name: email, dtype: int64

In [117]:
df.apply(len)

first    3
last     3
email    3
dtype: int64

In [118]:
df.apply(lambda x: x.min()) # Aplica uma função lambda a cada coluna do DataFrame, retornando o valor mínimo de cada coluna.
# A função lambda é uma função anônima que recebe um argumento x e retorna o valor mínimo de x usando o método min().

first                      Corey
last                     Matheus
email    COREYMSCHAFER@GMAIL.COM
dtype: str

USANDO A FUNÇÃO .map()

In [119]:
df['first'].map({'Corey': 'João', 'Jane': 'Janete'}) # Substitui os valores da coluna 'first' com base em um dicionário de mapeamento;
# onde as chaves são os valores originais e os valores são os novos valores a serem atribuídos.
# não alteram o DataFrame original, a menos que sejam atribuídos de volta à coluna ou ao DataFrame.

0      João
1    Janete
2       NaN
Name: first, dtype: str

In [120]:
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane    Smith        JANEDOE@EMAIL.COM
2   John  Matheus        MATHEUS@EMAIL.COM

In [121]:
df['first'].replace({'Corey': 'João', 'Jane': 'Janete'})
# o método replace é usado para substituir os valores da coluna 'first' com base em um dicionário de mapeamento,
# onde as chaves são os valores originais e os valores são os novos valores a serem atribuídos.

0      João
1    Janete
2      John
Name: first, dtype: str

In [122]:
df['first'] = df['first'].replace({'Corey': 'João', 'Jane': 'Janete'})
# O DataFrame df é atualizado com os novos valores na coluna 'first', onde 'Corey' é substituído por 'João' e 'Jane' é substituído por 'Janete'.

In [123]:
df

    first     last                    email
0    João  Schafer  COREYMSCHAFER@GMAIL.COM
1  Janete    Smith        JANEDOE@EMAIL.COM
2    John  Matheus        MATHEUS@EMAIL.COM